# Generated by Django 4.2 on 2023-04-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehiculo_marca_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Rol')),
                ('nomRol', models.CharField(max_length=50, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nomUser', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre del usuario')),
                ('correo', models.CharField(max_length=20, verbose_name='Corre electronico')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
    ]
