# Generated by Django 4.2 on 2023-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rol_usuario_rol_alter_usuario_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del genero')),
            ],
        ),
    ]
