# Generated by Django 4.2 on 2023-04-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.genero'),
            preserve_default=False,
        ),
    ]
